project_id = "jymgrlxabmzuzdfccuzv"

[functions.scan]
verify_jwt = false

[functions.gmail-auth]
verify_jwt = false

[functions.gmail-callback]
verify_jwt = false

[functions.gmail-emails]
verify_jwt = false
